package com.onyx.avhub.core.data.repository

import com.onyx.avhub.core.data.db.entity.EqPresetEntity

/** Standard 10-band ISO center frequencies, shared by every built-in preset. */
val TEN_BAND_CENTER_FREQ_HZ = listOf(31, 62, 125, 250, 500, 1000, 2000, 4000, 8000, 16000)

/**
 * Seed data inserted on first launch so the hub is useful before any user customization.
 *
 * IDs are fixed (rather than autogenerated) so re-seeding via upsert stays idempotent
 * instead of inserting duplicate rows on every app start.
 */
object BuiltInPresets {
    val FLAT = EqPresetEntity(
        id = 1,
        name = "Flat",
        bandCenterFreqHz = TEN_BAND_CENTER_FREQ_HZ,
        bandGainsDb = List(10) { 0f },
        isBuiltIn = true,
    )

    val BASS_BOOST = EqPresetEntity(
        id = 2,
        name = "Bass Boost",
        bandCenterFreqHz = TEN_BAND_CENTER_FREQ_HZ,
        bandGainsDb = listOf(6f, 5f, 4f, 2f, 0f, 0f, 0f, 0f, 0f, 0f),
        bassBoostStrength = 700,
        isBuiltIn = true,
    )

    val VOCAL_CLARITY = EqPresetEntity(
        id = 3,
        name = "Vocal Clarity",
        bandCenterFreqHz = TEN_BAND_CENTER_FREQ_HZ,
        bandGainsDb = listOf(-2f, -1f, 0f, 2f, 4f, 4f, 3f, 1f, 0f, -1f),
        isBuiltIn = true,
    )

    val CINEMA = EqPresetEntity(
        id = 4,
        name = "Cinema",
        bandCenterFreqHz = TEN_BAND_CENTER_FREQ_HZ,
        bandGainsDb = listOf(4f, 3f, 1f, 0f, -1f, 0f, 1f, 2f, 3f, 4f),
        virtualizerStrength = 500,
        isBuiltIn = true,
    )

    val ALL = listOf(FLAT, BASS_BOOST, VOCAL_CLARITY, CINEMA)
}
